### ISSUE TITLE
[split categorized] Legend is splitted but not the layer

### ISSUE THREAD

**Issue by acassand** [qwc-services/qwc-qgis-server-plugins#3] opened 2024-07-25 15:08 UTC
**Observed behaviour** :

- Even by following all steps written [here](https://qwc-services.github.io/master/configuration/ThemesConfiguration/#split-categorized-layers), I still do not succeed to display categorized layers as separate layers on QWC

- How my layer geographic_lines appears in QWC **without** convert_categorized_layer variable => 
![geographic_lines_legend_not_splitted](https://github.com/user-attachments/assets/41ea9a67-d153-4b38-81c2-6bf37c35fd9e)
![legend_not_splitted](https://github.com/user-attachments/assets/06b2618b-a684-4e6a-8b92-cfea30e7a222)

- How my layer geographic_lines appears in QWC **with** convert_categorized_layer variable => 
![geographic_lines_legend_splitted](https://github.com/user-attachments/assets/87f84ebf-d87c-4359-a768-e91bb8fafd24)
![legend_splitted](https://github.com/user-attachments/assets/4570bf1a-1425-4147-a164-252dbe0fa203)

**Expected behaviour** :

- geographic_lines should be splitted into two layers on QWC interface => something like this I think : 
![expected_behaviour](https://github.com/user-attachments/assets/7cbda785-b022-400f-bd42-6c35a4b2b157)

Attachments : 
[demo_acd_split_ko.zip](https://github.com/user-attachments/files/16379801/demo_acd_split_ko.zip)
- demo_acd_split_ko.zip which contains acd_not_splitted.qgs & acd_splitted.qgs

**Comment by manisandro** [comment] 2024-07-25 17:54
I think this is a duplicate of #2.

**Closed as completed by manisandro** 2024-07-25 17:54 UTC

**Comment by acassand** [comment] 2024-07-26 08:43
Not exactly the same issue, but solved with the same workaround. Thank you.
